### ISSUE TITLE
请问是否缺少了.sty文件？

### ISSUE THREAD

**Issue by bennyji** [kevinleeex/scu_thesis_2020#1]
你好，感谢你的分享。我下载你的模板，在win10系统下的TexStudio上运行，会报错，其中一个错误为找不到gtb7714.sty。

**Comment by kevinleeex** [comment]
> 你好，感谢你的分享。我下载你的模板，在win10系统下的TexStudio上运行，会报错，其中一个错误为找不到gtb7714.sty。

你好，不好意思，回复晚了。
请问你是基于Tex Live还是MikTex，它们都可以使用相应的包管理器添加此样式文件即可，若是基于Tex Live是会自动下载缺失包的，推荐先安装Tex Live。我已知的是使用CTEX的套件不会自带此库。

**Comment by bennyji** [comment]
好的，我试着安装一下Tex Live。谢谢你的解答。
