### ISSUE TITLE
放到overleaf里面编译报错

### ISSUE THREAD

**Issue by Chenliang-Gu** [kevinleeex/scu_thesis_2020#10]
把项目放在overleaf里面以后编译报错，如下图
![image](https://user-images.githubusercontent.com/30205347/140894199-939210d5-012c-48b4-9746-a44a1e039091.png)

**Comment by kevinleeex** [comment]
你好，这个项目没有经过overleaf测试，可以先尝试解决一下，我有空时看下，如果你已经解决，可以先关闭这个issue

**Comment by diggle1** [comment]
> 

我用texstudio也出现这个问题了
![image](https://user-images.githubusercontent.com/38290717/143545009-50d2602d-ebab-49fc-926d-6d087d5b1aea.png)

**Comment by Chenliang-Gu** [comment]
我已经调好了，overleaf编译器选XeLaTex，TeX Live version 选2019。麻烦作者写到readme里面，或者我提个PR？

**Comment by diggle1** [comment]
> 我已经调好了，overleaf编译器选XeLaTex，TeX Live version 选2019。麻烦作者写到readme里面，或者我提个PR？

请问下你的tex live2019是在哪下的，现在官网和清华镜像都只能看到2021版的

**Comment by Chenliang-Gu** [comment]
> > 我已经调好了，overleaf编译器选XeLaTex，TeX Live version 选2019。麻烦作者写到readme里面，或者我提个PR？
> 
> 请问下你的tex live2019是在哪下的，现在官网和清华镜像都只能看到2021版的

我用的在线的overleaf哈

**Comment by diggle1** [comment]
> > > 我已经调好了，overleaf编译器选XeLaTex，TeX Live version 选2019。麻烦作者写到readme里面，或者我提个PR？
> > 
> > 
> > 请问下你的tex live2019是在哪下的，现在官网和清华镜像都只能看到2021版的
> 
> 我用的在线的overleaf哈

其他都没变是吗，就只是你说的这个配置的问题

**Comment by Chenliang-Gu** [comment]
> > > > 我已经调好了，overleaf编译器选XeLaTex，TeX Live version 选2019。麻烦作者写到readme里面，或者我提个PR？
> > > 
> > > 
> > > 请问下你的tex live2019是在哪下的，现在官网和清华镜像都只能看到2021版的
> > 
> > 
> > 我用的在线的overleaf哈
> 
> 其他都没变是吗，就只是你说的这个配置的问题
en

**Comment by kevinleeex** [comment]
因为当时我是使用的2019的版本，更高版本可能会因为默认的一些包，尤其是ctex的版本带来的特性或语法不兼容，所以都是推荐的使用tex live 2019版本。
可以考虑使用高版本对模板加入兼容，我这周末看下吧。

**Comment by kevinleeex** [comment]
> 我已经调好了，overleaf编译器选XeLaTex，TeX Live version 选2019。麻烦作者写到readme里面，或者我提个PR？

Hi！你可以直接提一个pr写到readme的usages中，命名一个overleaf用户的使用方式。

**Comment by kevinleeex** [comment]
问题已解决，增加如下特性：
- 增加Overleaf用户指南
- 增加高版本Tex Live支持（CTEX兼容性支持）

**Comment by northword** [comment]
> 问题已解决，增加如下特性：
> 
> * 增加Overleaf用户指南
> * 增加高版本Tex Live支持（CTEX兼容性支持）

README Overleaf 指南中的链接无法访问内容，提示：Restricted, sorry you don’t have permission to load this page.

**Comment by kevinleeex** [comment]
> 
我使用了不同的浏览器，包括手机都是可以正常访问的，是无需登录即可访问的链接。如下
https://www.overleaf.com/read/mdcwrzbkmcjb

**Comment by northword** [comment]
> > 
> 
> 我使用了不同的浏览器，包括手机都是可以正常访问的，是无需登录即可访问的链接。如下 https://www.overleaf.com/read/mdcwrzbkmcjb

现在我也已经可以正常访问了，可能刚刚 overleaf 有一些延迟或是我这儿的一些问题。
感谢您维护的模板！
