### ISSUE TITLE
排版问题，怎么去除章节间的空白页面？

### ISSUE THREAD

**Issue by dlagez** [kevinleeex/scu_thesis_2020#17]
我使用了这个模版之后，发现摘要和下一章之间有一页的空白，如下图。怎么才能去除这个空白页面？

![image](https://user-images.githubusercontent.com/62829603/195997281-6f142d11-e3ab-48d6-b26b-617ec87fbc02.png)

**Comment by northword** [comment]
特性，为了使每一章都从奇数页开始。
似乎没有选项关闭，可以直接修改模板去除。
