### ISSUE TITLE
windows平台使用MikTex编译出来的pdf首页中的中文“题目/学位类别”等信息都没了

### ISSUE THREAD

**Issue by georgezzzh** [kevinleeex/scu_thesis_2020#18]
排版选项选择的是“XeLatex+makeIndex+BibTex", 编译出来的结果与预期差别太大，首页中的中文“题目/学位类别”等信息都没了。
![微信截图_20230209150309](https://user-images.githubusercontent.com/36061092/217741227-e03defe2-7c17-402c-b666-f13d9f7f1f69.png)

**Comment by kevinleeex** [comment]
目前没有在MikTex里面测试过，在TexLive和Overleaf中运行测试过，看你的截图，应该是所有的中文字符都没有编译成功，请根据编译错误信息排查一下问题。
或者使用推荐的配置和软件编译一下

**Comment by georgezzzh** [comment]
又重新下TexLive，直接用"XeLatex（编译选项）"编译成功了。终结！
