### ISSUE TITLE
请问能提供本科的模版吗

### ISSUE THREAD

**Issue by fucknamel** [kevinleeex/scu_thesis_2020#2]
非常感谢大佬的分享，请问大佬有计划出一个本科毕业论文的模版吗，卑微学弟在线乞讨

**Comment by kevinleeex** [comment]
> 非常感谢大佬的分享，请问大佬有计划出一个本科毕业论文的模版吗，卑微学弟在线乞讨

你好，由于我手上没有川大本科的写作规范，当时没有把本科包含进去，现在可以暂时参考[旧模版](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate)。

后续会对此项目进行**重构并规范化**，到时候有本科写作规范的话，可能会顺便支持本科论文。如果有，你也可以提供一份本科写作规范发送我的[邮箱](mailto:hello@lidengju.com)。

谢谢支持！

**Comment by fucknamel** [comment]
好的，规范已经发到您邮箱了，非常感谢大佬的分享！
