### ISSUE TITLE
模板对比

### ISSUE THREAD

**Issue by rxc205** [kevinleeex/scu_thesis_2020#4]
@kevinleeex ，您好，
    
- 我在另一处看见一个模板，似乎已经4年没有更新了。[https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate](url)。两者相比有何区别吗？

- 您当前的这个仓库下的模板适用于2021年的毕业论文写作吗？

- 作者还会持续对此模板进行更新吗？

**Comment by kevinleeex** [comment]
1. 本模版一开始参考了你发的[链接模版](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate)的一些基本配置，但实际根据2020年的四川大学研究生论文写作规范、格式等要求做了大量重写，并添加了更多特性，但链接模版也依旧在本仓库的致谢中。
2. 若2021年的研究生论文写作规范未做更新，则本模板依旧适用写作，请比对References目录中的PDF规范文件和你们21年下发的写作规范。
3. 本模版在规范没有变动的情况下本人不会再做更新，若有bug和issue会抽空进行修复更新。若规范有细节变动，可基于此模版fork一份副本进行改动并共享给其他人。如有源码贡献，可联系我加入本项目的致谢名单和项目链接，对此作者表示倡导和感谢。

**Comment by rxc205** [comment]
> 1. 本模版一开始参考了你发的[链接模版](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate)的一些基本配置，但实际根据2020年的四川大学研究生论文写作规范、格式等要求做了大量重写，并添加了更多特性，但链接模版也依旧在本仓库的致谢中。
> 2. 若2021年的研究生论文写作规范未做更新，则本模板依旧适用写作，请比对References目录中的PDF规范文件和你们21年下发的写作规范。
> 3. 本模版在规范没有变动的情况下本人不会再做更新，若有bug和issue会抽空进行修复更新。若规范有细节变动，可基于此模版fork一份副本进行改动并共享给其他人。如有源码贡献，可联系我加入本项目的致谢名单和项目链接，对此作者表示倡导和感谢。

谢谢解答！
