### ISSUE TITLE
如果遇到“已添加ReferenceBase.bib，但是仍然无法正常生成引用。”的情况，可以参看这个解决方案。

### ISSUE THREAD

**Issue by TonyDandelion** [kevinleeex/scu_thesis_2020#5]
运行环境
- MacBook Pro 2020
- Big Sur 11.2.1 (20D74)
- TeX Live 2020
- MacTex(on mac)
- Visual Studio Code (optional) with LaTex workshop plugin

复现
![image](https://user-images.githubusercontent.com/14906334/111565619-a66f5f80-87d6-11eb-96fe-d0ac1db74659.png)
![image](https://user-images.githubusercontent.com/14906334/111565682-c0a93d80-87d6-11eb-899f-0ec33b22af4b.png)

原因
xelatex无法编译 bib 文件，普通的 latex 编译器，需要手动一个编译大轮回解决这个问题：xelatex-bibtex-xelatex-xelatex。还好vscode提供了基于setting.json的 “命令集成”方案，可以接连执行四次不同的编译。

解决方法
1. 在vscode的setting.json中添加
```
  {
    "name": "xelatex -> bibtex -> xelatex*2",
    "tools": [
    "xelatex",
    "bibtex",
    "xelatex",
    "xelatex"
    ]
    }
```
2. 重启vscode之后，选择xelatex-bibtex-xelatex-xelatex编译。
![image](https://user-images.githubusercontent.com/14906334/111568129-27305a80-87db-11eb-90b2-2b15264e7991.png)

参考连接
https://zhuanlan.zhihu.com/p/71432461

PS：问题已经解决，这个issue可以直接关闭，仅提供参考作用。

**Comment by kevinleeex** [comment]
谢谢你的关注，该issue已关闭
