### ISSUE TITLE
请问如何添加附录？

### ISSUE THREAD

**Issue by TonyDandelion** [kevinleeex/scu_thesis_2020#6]
请问，该模板如何添加如下所示附录？
![image](https://user-images.githubusercontent.com/14906334/111864814-23006a80-899e-11eb-9fcd-9c2757d6b4ec.png)

**Comment by kevinleeex** [comment]
HI, 关于附录页，可以直接在`\backmatter`标记后，新增`\chapter{附录A}`标记，然后自行创建一个表格，通常你可以像其他模块一样新建文件，然后`include`进来。
