### ISSUE TITLE
照着学院给的模板....?

### ISSUE THREAD

**Issue by xdr940** [kevinleeex/scu_thesis_2020#8]
是计算机学院的嘛？ 学校没有统一模板吗？和我们学院（空天）老师给的完全不一样啊T T

**Comment by northword** [comment]
建环甚至要求纸张16K而不是A4，可以考虑自己改改

**Comment by xdr940** [comment]
> 建环甚至要求纸张16K而不是A4，可以考虑自己改改

我们也是！可能是学校统一的word

**Comment by kevinleeex** [comment]
这就尴尬了，我以为学院应该给的是学校统一模板，改好欢迎拉个分支啊...
